'use strict';

/**
 * Offline two-seat arena for bot evaluation.
 *
 * This harness bundles the authoritative ../../src/game-engine.ts directly. It
 * intentionally does not use bot-template/anti-human-bot/reference (which may
 * be a stale checkout or symlink). Every seat receives its own full/diff frame
 * generated by the engine, including fog-of-war when enabled.
 */
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const vm = require('node:vm');
const { createHash } = require('node:crypto');
const { deflateSync, inflateSync } = require('node:zlib');
const { performance } = require('node:perf_hooks');
const { BoardState } = require('../../anti-human-bot/bot/state.cjs');

const ROOT = path.resolve(__dirname, '../../..');
const ENGINE_PATH = path.join(ROOT, 'src/game-engine.ts');
const MAP_MODES = ['random', 'maze', 'archipelago', 'mediterranean'];
const bundleCache = new Map();
const simpleScriptCache = new Map();

// Fixed memory per seat, mergeable without retaining individual decisions.
// Positive timing buckets have at most 2% relative width; values below 0.0001 ms
// share the first bucket. Exact count, sum and maximum are retained separately.
const TIMING_BINS = 2048;
const TIMING_MIN_MS = 0.0001;
const TIMING_RATIO = 1.02;
const TIMING_LOG_RATIO = Math.log(TIMING_RATIO);
const MAX_REPLAY_BYTES = 8 * 1024 * 1024;
const MAX_TRACE_BYTES = 2 * 1024 * 1024;

function createTimingStats() {
  return { counts: new Float64Array(TIMING_BINS), count: 0, sumMs: 0, maxMs: 0 };
}
function recordTiming(stats, elapsed) {
  if (!Number.isFinite(elapsed) || elapsed < 0) throw new Error('invalid decision duration');
  const index =
    elapsed < TIMING_MIN_MS
      ? 0
      : Math.min(TIMING_BINS - 1, 1 + Math.floor(Math.log(elapsed / TIMING_MIN_MS) / TIMING_LOG_RATIO));
  stats.counts[index] += 1;
  stats.count += 1;
  stats.sumMs += elapsed;
  stats.maxMs = Math.max(stats.maxMs, elapsed);
}
function mergeTiming(target, source) {
  if (!source) return;
  if (source.counts.length !== TIMING_BINS) throw new Error('incompatible timing histogram');
  for (let index = 0; index < TIMING_BINS; index += 1) target.counts[index] += source.counts[index];
  target.count += source.count;
  target.sumMs += source.sumMs;
  target.maxMs = Math.max(target.maxMs, source.maxMs);
}
function timingPercentile(stats, percentile) {
  if (!stats.count) return 0;
  const rank = Math.ceil((stats.count * percentile) / 100);
  let seen = 0;
  for (let index = 0; index < TIMING_BINS; index += 1) {
    seen += stats.counts[index];
    if (seen >= rank) {
      const upper = index === TIMING_BINS - 1 ? stats.maxMs : TIMING_MIN_MS * TIMING_RATIO ** index;
      return Math.min(stats.maxMs, upper);
    }
  }
  throw new Error('invalid timing histogram count');
}
function createMetrics() {
  return { decisions: 0, timing: createTimingStats(), timeouts: 0, emitted: 0, rejected: 0 };
}
function engineSnapshot(engine) {
  const fields = [
    'n',
    'm',
    'turn',
    'gridType',
    'owner',
    'armyCnt',
    'isolated',
    'isolatedAge',
    'st',
    'generals',
    'pstat',
    'deadCount',
    'deadOrder',
    'spec',
  ];
  return structuredClone(Object.fromEntries(fields.map((key) => [key, engine[key]])));
}
function snapshotHash(snapshot) {
  return createHash('sha256').update(JSON.stringify(snapshot)).digest('hex');
}

function compileEngine({ synchronous = true } = {}) {
  const key = `${synchronous}:${fs.statSync(ENGINE_PATH).mtimeMs}`;
  const cached = bundleCache.get(key);
  if (cached) return cached;
  const source0 = fs.readFileSync(ENGINE_PATH, 'utf8');
  let source = source0;
  if (synchronous) {
    for (const [name, result] of [
      ['initializeMap', 'void'],
      ['gameTick', 'boolean'],
    ]) {
      const header = `private async ${name}(): Promise<${result}> {`;
      const start = source.indexOf(header);
      const end = source.indexOf('\n  }', start);
      if (start < 0 || end < 0) throw new Error(`engine interface changed: ${name}`);
      let body = source.slice(start, end);
      const awaitCount = (body.match(/\bawait\b/g) || []).length;
      if (
        awaitCount !== (name === 'gameTick' ? 1 : 0) ||
        (name === 'gameTick' && !body.includes('await this.sendMap(gameEnd);'))
      ) {
        throw new Error(`engine async contract changed: ${name}`);
      }
      body = body
        .replace(header, `private ${name}(): ${result} {`)
        .replace('await this.sendMap(gameEnd);', 'this.sendMap(gameEnd);');
      source = source.slice(0, start) + body + source.slice(end);
    }
  }
  const esbuild = require('esbuild');
  const built = esbuild.buildSync({
    stdin: { contents: source, sourcefile: ENGINE_PATH, resolveDir: path.dirname(ENGINE_PATH), loader: 'ts' },
    bundle: true,
    platform: 'node',
    format: 'cjs',
    target: 'node18',
    write: false,
    external: ['better-sqlite3', 'sqlite3'],
    logLevel: 'silent',
  });
  const compiled = new Module(`${ENGINE_PATH}.arena.cjs`, module);
  compiled.filename = `${ENGINE_PATH}.arena.cjs`;
  compiled.paths = Module._nodeModulePaths(path.dirname(ENGINE_PATH));
  compiled._compile(built.outputFiles[0].text, compiled.filename);
  bundleCache.set(key, compiled.exports);
  return compiled.exports;
}

function createVirtualSocket(sid, timer) {
  const listeners = new Map();
  const outgoing = [];
  const socket = {
    id: sid,
    connected: true,
    on(name, fn) {
      const list = listeners.get(name) || [];
      list.push(fn);
      listeners.set(name, list);
      return socket;
    },
    off(name, fn) {
      const list = listeners.get(name) || [];
      listeners.set(
        name,
        list.filter((item) => item !== fn),
      );
      return socket;
    },
    emit(name, payload) {
      if (name === 'attack' && payload && typeof payload === 'object') {
        outgoing.push({ kind: 'attack', ...payload });
      } else if (name === 'build' && payload && typeof payload === 'object') {
        outgoing.push({ kind: 'build', ...payload });
      } else if (name === 'clear_queue' || name === 'pop_queue') {
        outgoing.push({ kind: name });
      }
      return true;
    },
    trigger(name, payload) {
      const list = listeners.get(name) || [];
      for (const fn of list.slice()) fn(payload);
    },
    drain() {
      return outgoing.splice(0, outgoing.length);
    },
    pending() {
      return outgoing.length;
    },
  };
  socket.timer = timer;
  return socket;
}

function makeTimerContext() {
  let seq = 1;
  const queue = [];
  const canceled = new Set();
  const timer = {
    setTimeout(fn, _delay, ...args) {
      const id = seq++;
      queue.push({ id, fn, args });
      return id;
    },
    clearTimeout(id) {
      canceled.add(id);
    },
    setInterval(fn, _delay, ...args) {
      // heartbeat is disabled in the adapter; retaining one-shot semantics is
      // safer than allowing a background interval to run forever in a match.
      const id = seq++;
      queue.push({ id, fn, args, interval: true });
      return id;
    },
    clearInterval(id) {
      canceled.add(id);
    },
    flush(limit = 1000) {
      let ran = 0;
      while (queue.length && ran < limit) {
        const item = queue.shift();
        if (canceled.has(item.id)) continue;
        item.fn(...item.args);
        ran += 1;
        if (item.interval && !canceled.has(item.id)) queue.push(item);
      }
      if (queue.length) throw new Error('virtual timer queue exceeded limit');
      return ran;
    },
  };
  return timer;
}

function resolveVmModule(from, spec) {
  if (!spec.startsWith('.')) return null;
  const base = path.resolve(path.dirname(from), spec);
  const candidates = [
    base,
    `${base}.js`,
    `${base}.cjs`,
    path.join(base, 'index.js'),
    path.join(base, 'index.cjs'),
  ];
  return candidates.find((candidate) => fs.existsSync(candidate) && fs.statSync(candidate).isFile()) || null;
}

function loadSimpleAttach(timer) {
  const entry = path.join(ROOT, 'bot-template/simple-strategy-bot/strategy.js');
  const context = vm.createContext({
    console: { log() {}, error() {}, warn() {} },
    process: { env: { ...process.env } },
    Buffer,
    URL,
    TextEncoder,
    TextDecoder,
    setTimeout: timer.setTimeout,
    clearTimeout: timer.clearTimeout,
    setInterval: timer.setInterval,
    clearInterval: timer.clearInterval,
  });
  const cache = new Map();
  function load(filename) {
    const full = path.resolve(filename);
    if (cache.has(full)) return cache.get(full).exports;
    const code = fs.readFileSync(full, 'utf8');
    const mod = { exports: {} };
    cache.set(full, mod);
    const localRequire = (spec) => {
      const resolved = resolveVmModule(full, spec);
      return resolved ? load(resolved) : require(spec);
    };
    const wrapper = `(function (exports, require, module, __filename, __dirname) {\n${code}\n})`;
    const stamp = `${full}:${fs.statSync(full).mtimeMs}`;
    let script = simpleScriptCache.get(stamp);
    if (!script) {
      script = new vm.Script(wrapper, { filename: full });
      simpleScriptCache.set(stamp, script);
    }
    const fn = script.runInContext(context);
    fn(mod.exports, localRequire, mod, full, path.dirname(full));
    return mod.exports;
  }
  const exports = load(entry);
  return exports;
}

function makeSimpleAdapter({ seat, sid, decisionTimeoutMs = 40 } = {}) {
  const timer = makeTimerContext();
  const socket = createVirtualSocket(sid || `arena-${seat}`, timer);
  const { attachStrategy } = loadSimpleAttach(timer);
  const metrics = createMetrics();
  let attached = false;
  let lastError = null;
  const run = (fn) => {
    const t0 = performance.now();
    try {
      const out = fn();
      timer.flush();
      const elapsed = performance.now() - t0;
      metrics.decisions += 1;
      recordTiming(metrics.timing, elapsed);
      if (elapsed > decisionTimeoutMs) metrics.timeouts += 1;
      return out;
    } catch (error) {
      lastError = error;
      throw error;
    }
  };
  return {
    kind: 'simple',
    seat,
    socket,
    metrics,
    attach() {
      if (attached) return;
      attached = true;
      attachStrategy(socket, {
        room: 'offline-arena',
        autoReady: false,
        actionDelayMs: 0,
        heartbeatIntervalMs: 0,
        log: () => {},
      });
      socket.trigger('connect');
      timer.flush();
    },
    receive(event, payload) {
      if (!attached) return;
      if (event === 'update' && !payload.game_end) run(() => socket.trigger(event, payload));
      else socket.trigger(event, payload);
    },
    drain() {
      const actions = socket.drain();
      metrics.emitted += actions.length;
      return actions;
    },
    error() {
      return lastError;
    },
  };
}

function createArena({
  mapMode = 'random',
  seed = 'default',
  mapSize = 0.5,
  fog = false,
  synchronous = true,
  adapters = [],
  traceLimit = 120,
  captureReplay = traceLimit > 0,
} = {}) {
  if (!MAP_MODES.includes(mapMode)) throw new Error(`unsupported map: ${mapMode}`);
  if (!Number.isFinite(mapSize) || mapSize < 0.2 || mapSize > 3)
    throw new Error('mapSize must be in [0.2, 3]');
  const { GameEngine } = compileEngine({ synchronous });
  const sids = ['arena-0', 'arena-1'];
  const states = [];
  const stats = sids.map((_, player) => ({ player, attacks: 0, builds: 0, upgrades: 0, rejected: 0 }));
  const decision = sids.map(() => createMetrics());
  const trace = [];
  let traceBytes = 0;
  const actionLines = [];
  let replayBytes = 0;
  let replayTruncated = false;
  let initialSnapshot = null;
  let ended = false;
  let result = null;
  const bySeat = new Map(adapters.filter(Boolean).map((adapter) => [adapter.seat, adapter]));
  const pushTrace = (row) => {
    if (traceLimit <= 0) return;
    trace.push(row);
    traceBytes += Buffer.byteLength(JSON.stringify(row));
    while (trace.length > traceLimit || traceBytes > MAX_TRACE_BYTES) {
      const removed = trace.shift();
      traceBytes -= Buffer.byteLength(JSON.stringify(removed));
    }
  };
  const updateSeat = (p, payload) => {
    const state = states[p];
    if (!state) return;
    state.apply(payload);
    const adapter = bySeat.get(p);
    if (adapter) adapter.receive('update', payload);
  };
  const engine = new GameEngine(
    {
      width_ratio: mapSize,
      height_ratio: mapSize,
      map_size_version: 2,
      city_ratio: 0,
      mountain_ratio: 0,
      swamp_ratio: 0.05,
      speed: 1,
      allow_team: false,
      fog: Boolean(fog),
      map_token: String(seed),
      map_mode: mapMode,
      player_names: sids,
      player_teams: [1, 2],
    },
    sids,
    sids,
    '__offline_arena__',
    {
      update(sid, payload) {
        updateSeat(sids.indexOf(sid), payload);
      },
      emitInitMap(sid, init) {
        const p = sids.indexOf(sid);
        states[p] = new BoardState(init, sid);
        const adapter = bySeat.get(p);
        if (adapter) adapter.receive('init_map', init);
      },
      chatMessage() {},
      endGame(_gid, entries) {
        result = entries;
      },
      md5: (input) => input,
      replayStore: {
        saveReplay() {
          return '';
        },
      },
    },
  );
  const initialization = engine.initializeMap();
  if (initialization && typeof initialization.then === 'function') {
    throw new Error('synchronous engine initialization unexpectedly returned a Promise');
  }
  engine.enableAfkSurrender = false;
  engine.selectGenerals();
  for (let p = 0; p < 2; p += 1) {
    const adapter = bySeat.get(p);
    if (adapter) {
      adapter.attach();
      adapter.socket.trigger('set_id', sids[p]);
    }
    engine.emitInitMap(sids[p], { n: engine.n, m: engine.m, player_ids: sids, general: engine.generals[p] });
  }
  // Full frame each tick keeps the offline protocol simple while exercising
  // the exact per-player fog filter and payload shape.
  engine.recordReplayTurnMoves = () => {};
  engine.sendMap = (gameEnd) => {
    const kills = engine.recentKills;
    engine.recentKills = {};
    const leaderboard = engine.buildLeaderboard();
    for (let p = 0; p < 2; p += 1) {
      const payload = engine.buildFullFramePayload(p, gameEnd);
      payload.leaderboard = leaderboard;
      payload.kills = kills;
      payload.lst_move = engine.toMovePayload(engine.lstMove[p], engine.lstSkip[p]);
      updateSeat(p, payload);
      if (engine.lstMove[p]) {
        const op = engine.lstMove[p];
        if (op.kind === 'm') stats[p].attacks += 1;
        else if (op.kind === 'b') stats[p].builds += 1;
        else stats[p].upgrades += 1;
      }
      stats[p].rejected += engine.lstSkip[p];
      engine.lstMove[p] = null;
      engine.lstSkip[p] = 0;
    }
    ended = Boolean(gameEnd);
  };
  engine.sendMap(false);
  if (captureReplay) initialSnapshot = engineSnapshot(engine);

  function submit(player, action) {
    if (action == null) return;
    if (captureReplay && !replayTruncated) {
      const line = `${JSON.stringify([engine.turn + 1, player, action])}\n`;
      replayBytes += Buffer.byteLength(line);
      if (replayBytes <= MAX_REPLAY_BYTES) actionLines.push(line);
      else replayTruncated = true;
    }
    if (action.kind === 'clear_queue') {
      engine.clearQueue(sids[player]);
      return;
    }
    if (action.kind === 'pop_queue') {
      engine.popQueue(sids[player]);
      return;
    }
    if (
      !action ||
      !['attack', 'build'].includes(action.kind) ||
      !Number.isInteger(action.x) ||
      !Number.isInteger(action.y)
    ) {
      decision[player].rejected += 1;
      return;
    }
    try {
      if (action.kind === 'attack') {
        const mode = action.mode ?? 0;
        if (!Number.isInteger(action.dx) || !Number.isInteger(action.dy) || ![0, 1, 2].includes(mode))
          throw new Error('invalid attack');
        engine.addMove(sids[player], action.x, action.y, action.dx, action.dy, mode);
      } else {
        const op = action.op ?? 'b';
        if (!['b', 'c'].includes(op)) throw new Error('invalid build');
        engine.addBuild(sids[player], action.x, action.y, op);
      }
    } catch (_) {
      decision[player].rejected += 1;
    }
  }

  function drainAdapters() {
    const drained = [[], []];
    for (let p = 0; p < 2; p += 1) {
      const adapter = bySeat.get(p);
      if (!adapter) continue;
      const actions = adapter.drain();
      drained[p] = actions;
      for (const action of actions) submit(p, action);
      decision[p].decisions += adapter.metrics.decisions;
      mergeTiming(decision[p].timing, adapter.metrics.timing);
      adapter.metrics.timing = createTimingStats();
      decision[p].timeouts += adapter.metrics.timeouts;
      decision[p].emitted += adapter.metrics.emitted;
      adapter.metrics.decisions = 0;
      adapter.metrics.timeouts = 0;
      adapter.metrics.emitted = 0;
    }
    return drained;
  }

  function tick(actions = [null, null]) {
    if (ended) return true;
    const adapterActions = drainAdapters();
    actions.forEach((action, p) => submit(p, action));
    const current = engine.gameTick();
    if (current && typeof current.then === 'function')
      throw new Error('synchronous engine tick unexpectedly returned a Promise');
    if (current && result === null) engine.finishGame?.();
    pushTrace({
      turn: engine.turn,
      actions: actions.map((a) => (a ? { ...a } : null)),
      adapterActions,
      queues: sids.map((_, p) => engine.pmove[p]?.length || 0),
      players: engine.buildLeaderboard().map(({ id, army, land, class_ }) => ({ id, army, land, class_ })),
      rejected: stats.map((entry) => entry.rejected),
      ended: Boolean(current),
    });
    return Boolean(current);
  }

  return {
    engine,
    states,
    stats,
    decision,
    adapters: bySeat,
    get ended() {
      return ended;
    },
    get result() {
      return result;
    },
    get trace() {
      return trace.slice();
    },
    get replay() {
      if (!captureReplay) return null;
      return {
        schemaVersion: 1,
        settings: { mapMode, seed, mapSize, fog },
        initial: initialSnapshot,
        totalTicks: engine.turn,
        complete: !replayTruncated,
        maxUncompressedActionBytes: MAX_REPLAY_BYTES,
        actionEncoding: 'deflate-base64-jsonl-v1',
        actionData: deflateSync(actionLines.join('')).toString('base64'),
        finalStateSha256: snapshotHash(engineSnapshot(engine)),
      };
    },
    initialization,
    submit,
    tick,
    drainAdapters,
  };
}

function metricsSummary(row) {
  // Compatibility for standalone consumers of the earlier arena API. Long
  // evaluations use the bounded histogram throughout, including in workers.
  const timing = row.timing || createTimingStats();
  if (!row.timing) for (const duration of row.durationsMs || []) recordTiming(timing, duration);
  return {
    decisions: row.decisions || 0,
    measuredDecisions: timing.count,
    p50Ms: timingPercentile(timing, 50),
    p95Ms: timingPercentile(timing, 95),
    percentileEstimation: {
      method: 'log-histogram-upper-bound',
      bins: TIMING_BINS,
      relativeBucketWidth: TIMING_RATIO - 1,
      subResolutionMs: TIMING_MIN_MS,
      overflowFromMs: TIMING_MIN_MS * TIMING_RATIO ** (TIMING_BINS - 2),
    },
    meanMs: timing.count ? timing.sumMs / timing.count : 0,
    maxMs: timing.maxMs,
    maxIsExact: true,
    rejections: row.rejected || 0,
    timeouts: row.timeouts || 0,
    emitted: row.emitted || 0,
  };
}

// Reapply the recorded socket submissions, including queue clearing, to the
// authoritative engine. No policy or original random map generator is needed
// after the explicit initial board has been restored.
function replayMatch(replay) {
  if (!replay || replay.schemaVersion !== 1 || replay.actionEncoding !== 'deflate-base64-jsonl-v1') {
    throw new Error('unsupported arena replay');
  }
  if (!replay.complete) throw new Error('arena replay action limit exceeded; replay is incomplete');
  const arena = createArena({ ...replay.settings, traceLimit: 0, captureReplay: false });
  Object.assign(arena.engine, structuredClone(replay.initial));
  arena.engine.sendMap(false);
  const decoded = inflateSync(Buffer.from(replay.actionData, 'base64'), {
    maxOutputLength: MAX_REPLAY_BYTES,
  }).toString('utf8');
  const events = decoded
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line));
  let cursor = 0;
  while (!arena.ended && arena.engine.turn < replay.totalTicks) {
    while (cursor < events.length && events[cursor][0] === arena.engine.turn + 1) {
      const [, player, action] = events[cursor++];
      arena.submit(player, action);
    }
    arena.tick();
  }
  const actualHash = snapshotHash(engineSnapshot(arena.engine));
  return {
    matches: actualHash === replay.finalStateSha256,
    actualHash,
    expectedHash: replay.finalStateSha256,
    turns: arena.engine.turn,
    ended: arena.ended,
    stats: arena.engine.buildLeaderboard(),
  };
}

function structureTelemetry(engine, player, actionStats = null) {
  const owners = engine.owner || [];
  const grid = engine.gridType || [];
  let crowns = 0;
  let cities = 0;
  let army = 0;
  let land = 0;
  for (let x = 0; x < owners.length; x += 1) {
    for (let y = 0; y < (owners[x]?.length || 0); y += 1) {
      if (owners[x][y] !== player + 1) continue;
      const tile = grid[x]?.[y];
      const troops = Number(engine.armyCnt?.[x]?.[y]) || 0;
      army += troops;
      land += 1;
      if (tile === -2) crowns += 1;
      else if (tile === -1) cities += 1;
    }
  }
  return {
    crowns,
    cities,
    army,
    land,
    attacks: Number(actionStats?.attacks) || 0,
    builds: Number(actionStats?.builds) || 0,
    upgrades: Number(actionStats?.upgrades) || 0,
  };
}

function recordMatchTelemetry(telemetry, engine, turn, actionStats = null) {
  for (let player = 0; player < 2; player += 1) {
    const sample = structureTelemetry(engine, player, actionStats?.[player]);
    telemetry.maxCrowns[player] = Math.max(telemetry.maxCrowns[player], sample.crowns);
    telemetry.maxCities[player] = Math.max(telemetry.maxCities[player], sample.cities);
    if (turn >= telemetry.nextCheckpoint[player]) {
      for (const checkpoint of telemetry.checkpoints) {
        if (checkpoint > turn || telemetry.byTurn[player][checkpoint]) continue;
        telemetry.byTurn[player][checkpoint] = sample;
      }
      telemetry.nextCheckpoint[player] =
        telemetry.checkpoints.find((checkpoint) => checkpoint > turn) ?? Infinity;
    }
  }
}

function runMatch({
  mapMode = 'random',
  seed = 'default',
  maxTurns = 600,
  mapSize = 0.5,
  fog = false,
  policies = [null, null],
  adapters = [],
  traceLimit = 120,
  decisionTimeoutMs = 40,
} = {}) {
  if (!Number.isInteger(maxTurns) || maxTurns < 0) throw new Error('maxTurns must be a non-negative integer');
  const started = performance.now();
  const arena = createArena({ mapMode, seed, mapSize, fog, adapters, traceLimit });
  const checkpoints = [120, 300, 600, 900, 1200];
  const telemetry = {
    checkpoints,
    maxCrowns: [0, 0],
    maxCities: [0, 0],
    nextCheckpoint: [checkpoints[0], checkpoints[0]],
    byTurn: [Object.create(null), Object.create(null)],
  };
  recordMatchTelemetry(telemetry, arena.engine, arena.engine.turn, arena.stats);
  const ownPolicies = Array.isArray(policies) ? policies : [null, null];
  while (!arena.ended && arena.engine.turn < maxTurns) {
    const actions = [0, 1].map((p) => {
      const policy = ownPolicies[p];
      if (typeof policy !== 'function' || arena.states[p]?.dead) return null;
      const t0 = performance.now();
      let action = null;
      try {
        action = policy(arena.states[p]);
      } finally {
        const elapsed = performance.now() - t0;
        arena.decision[p].decisions += 1;
        recordTiming(arena.decision[p].timing, elapsed);
        if (elapsed > decisionTimeoutMs) arena.decision[p].timeouts += 1;
      }
      if (action) arena.decision[p].emitted += 1;
      return action;
    });
    arena.tick(actions);
    recordMatchTelemetry(telemetry, arena.engine, arena.engine.turn, arena.stats);
  }
  arena.drainAdapters();
  const leaderboard = arena.engine.buildLeaderboard();
  const alive = leaderboard.filter((p) => p.class_ !== 'dead');
  const winner = arena.ended && alive.length === 1 ? alive[0].id - 1 : null;
  return {
    winner,
    turns: arena.engine.turn,
    ended: arena.ended,
    stats: arena.stats.map((stat, p) => ({ ...stat, ...leaderboard.find((entry) => entry.id === p + 1) })),
    decision: arena.decision.map((row, p) =>
      metricsSummary({ ...row, rejected: row.rejected + arena.stats[p].rejected }),
    ),
    decisionHistograms: arena.decision.map((row) => row.timing),
    replay: arena.replay,
    elapsedMs: performance.now() - started,
    trace: arena.trace,
    telemetry: {
      checkpoints,
      players: telemetry.byTurn,
      maxCrowns: telemetry.maxCrowns,
      maxCities: telemetry.maxCities,
    },
  };
}

module.exports = {
  MAP_MODES,
  compileEngine,
  loadEngine: compileEngine,
  createArena,
  makeSimpleAdapter,
  runMatch,
  metricsSummary,
  createTimingStats,
  recordTiming,
  mergeTiming,
  createMetrics,
  replayMatch,
};
